const univs = [
  {"shortName": "Alger1", "wilaya": 'wilayas.Alger' },
  {"shortName": "Alger2", "wilaya": 'wilayas.Alger' },
  {"shortName": "Alger3", "wilaya": 'wilayas.Alger' },
  {"shortName": "USTHB", "wilaya": 'wilayas.Alger' },
  {"shortName": "Blida1", "wilaya": 'wilayas.Blida' },
  {"shortName": "Blida2", "wilaya": 'wilayas.Blida' },
  {"shortName": "UBM", "wilaya": 'wilayas.Boumerdès' },
  {"shortName": "UMMTO", "wilaya": 'wilayas.Tizi Ouzou' },
  {"shortName": "UAMB", "wilaya": 'wilayas.Béjaïa' },
  {"shortName": "UFAS1", "wilaya": 'wilayas.Sétif' },
  {"shortName": "Setif2", "wilaya": 'wilayas.Sétif' },
  {"shortName": "Constantine1", "wilaya": 'wilayas.Constantine' },
  {"shortName": "Constantine2", "wilaya": 'wilayas.Constantine' },
  {"shortName": "Constantine3", "wilaya": 'wilayas.Constantine' },
  {"shortName": "UBMA", "wilaya": 'wilayas.Annaba' },
  {"shortName": "UABT", "wilaya": 'wilayas.Tlemcen' },
  {"shortName": "UO1", "wilaya": 'wilayas.Oran' },
  {"shortName": "UO2", "wilaya": 'wilayas.Oran' },
  {"shortName": "USTOMB", "wilaya": 'wilayas.Oran' },
  {"shortName": "UAM", "wilaya": 'wilayas.Mostaganem' },
  {"shortName": "UIKT", "wilaya": 'wilayas.Tiaret' },
  {"shortName": "Laghouat", "wilaya": 'wilayas.Laghouat' },
  {"shortName": "UMB", "wilaya": 'wilayas.Biskra' },
  {"shortName": "UMBM", "wilaya": 'wilayas.M’Sila' },
  {"shortName": "UKMO", "wilaya": 'wilayas.Ouargla' },
  {"shortName": "UDJ", "wilaya": 'wilayas.Djelfa' },
  {"shortName": "ULTT", "wilaya": 'wilayas.Tébessa' },
  {"shortName": "UCB", "wilaya": 'wilayas.El Tarf' },
  {"shortName": "GHARDAIA", "wilaya": 'wilayas.Ghardaia' },
  {"shortName": "Jijel", "wilaya": 'wilayas.Jijel' },
  {"shortName": "ENP", "wilaya": 'wilayas.Alger' },
  {"shortName": "ESI", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENSTTIC", "wilaya": 'wilayas.Oran' },
  {"shortName": "ENSEE", "wilaya": 'wilayas.Boumerdès' },
  {"shortName": "ENSTP", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENST", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENSA", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENSV", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENSM", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENSKouba", "wilaya": 'wilayas.Alger' },
  {"shortName": "ENSC", "wilaya": 'wilayas.Constantine' },
  {"shortName": "ENSOran", "wilaya": 'wilayas.Oran' },
  {"shortName": "other", "wilaya": 'control.other' }
]

const levels = [
  { name: 'levels.l1', value: 'l1' },
  { name: 'levels.l2', value: 'l2' },
  { name: 'levels.l3', value: 'l3' },
  { name: 'levels.m1', value: 'm1' },
  { name: 'levels.m2', value: 'm2' },
  { name: 'levels.eng1', value: 'eng1' },
  { name: 'levels.eng2', value: 'eng2' },
  { name: 'levels.eng3', value: 'eng3' },
  { name: 'levels.eng4', value: 'eng4' },
  { name: 'levels.eng5', value: 'eng5' },
];

const specialities = [
  { name: 'specialities.CS', value: 'CS' },
  { name: 'specialities.IS', value: 'IS' },
  { name: 'specialities.SE', value: 'SE' },
  { name: 'specialities.AI', value: 'AI' },
  { name: 'specialities.DS', value: 'DS' },
  { name: 'specialities.MATH', value: 'MATH' },
  { name: 'specialities.APPMATH', value: 'APPMATH' },
  { name: 'specialities.PHYS', value: 'PHYS' },
  { name: 'specialities.APPHYS', value: 'APPHYS' },
  { name: 'specialities.CHEM', value: 'CHEM' },
  { name: 'specialities.INDCHEM', value: 'INDCHEM' },
  { name: 'specialities.ELEC', value: 'ELEC' },
  { name: 'specialities.TEL', value: 'TEL' },
  { name: 'specialities.AUTOC', value: 'AUTOC' },
  { name: 'specialities.RE', value: 'RE' },
  { name: 'specialities.BIO', value: 'BIO' },
  { name: 'specialities.BIOCHEM', value: 'BIOCHEM' },
  { name: 'specialities.MICRO', value: 'MICRO' },
  { name: 'specialities.GEN', value: 'GEN' },
  { name: 'specialities.ECOENV', value: 'ECOENV' },
  { name: 'specialities.BIOTECH', value: 'BIOTECH' },
  { name: 'specialities.FOOD', value: 'FOOD' },
  { name: 'specialities.AGRON', value: 'AGRON' },
  { name: 'specialities.ANIM', value: 'ANIM' },
  { name: 'specialities.PLANT', value: 'PLANT' },
  { name: 'specialities.ECON', value: 'ECON' },
  { name: 'specialities.MGMT', value: 'MGMT' },
  { name: 'specialities.BA', value: 'BA' },
  { name: 'specialities.ACC', value: 'ACC' },
  { name: 'specialities.FIN', value: 'FIN' },
  { name: 'specialities.BANK', value: 'BANK' },
  { name: 'specialities.MKT', value: 'MKT' },
  { name: 'specialities.INTTRADE', value: 'INTTRADE' },
  { name: 'specialities.MIS', value: 'MIS' },
  { name: 'specialities.PLAW', value: 'PLAW' },
  { name: 'specialities.LAW', value: 'LAW' },
  { name: 'specialities.BL', value: 'BL' },
  { name: 'specialities.ILAW', value: 'ILAW' },
  { name: 'specialities.POLSCI', value: 'POLSCI' },
  { name: 'specialities.INTREL', value: 'INTREL' },
  { name: 'specialities.ADMIN', value: 'ADMIN' },
  { name: 'specialities.PSY', value: 'PSY' },
  { name: 'specialities.SOC', value: 'SOC' },
  { name: 'specialities.PHIL', value: 'PHIL' },
  { name: 'specialities.HIST', value: 'HIST' },
  { name: 'specialities.GEO', value: 'GEO' },
  { name: 'specialities.ICS', value: 'ICS' },
  { name: 'specialities.LIBDOC', value: 'LIBDOC' },
  { name: 'specialities.ENG', value: 'ENG' },
  { name: 'specialities.FR', value: 'FR' },
  { name: 'specialities.AR', value: 'AR' },
  { name: 'specialities.TRANS', value: 'TRANS' },
  { name: 'specialities.LING', value: 'LING' },
  { name: 'specialities.EDU', value: 'EDU' },
  { name: 'specialities.PRIMARY', value: 'PRIMARY' },
  { name: 'specialities.MATHEDU', value: 'MATHEDU' },
  { name: 'specialities.PHYSEDU', value: 'PHYSEDU' },
  { name: 'specialities.ENGLT', value: 'ENGLT' },
  { name: 'specialities.FRLT', value: 'FRLT' },
  { name: 'specialities.ARLT', value: 'ARLT' },
  { name: 'specialities.STAT', value: 'STAT' },
  { name: 'specialities.OR', value: 'OR' },
  { name: 'specialities.DEM', value: 'DEM' },
  { name: 'specialities.URBAN', value: 'URBAN' },
  { name: 'specialities.MED', value: 'MED' },
  { name: 'specialities.PHARM', value: 'PHARM' },
  { name: 'specialities.DENT', value: 'DENT' },
  { name: 'specialities.VET', value: 'VET' },
  { name: 'specialities.NURS', value: 'NURS' },
  { name: 'specialities.MEDIMG', value: 'MEDIMG' },
  { name: 'specialities.LAB', value: 'LAB' },
  { name: 'specialities.PUBHLTH', value: 'PUBHLTH' },
  { name: 'specialities.CIVENG', value: 'CIVENG' },
  { name: 'specialities.MECHENG', value: 'MECHENG' },
  { name: 'specialities.ELECENG', value: 'ELECENG' },
  { name: 'specialities.MECH', value: 'MECH' },
  { name: 'specialities.INDENG', value: 'INDENG' },
  { name: 'specialities.PROCENG', value: 'PROCENG' },
  { name: 'specialities.MATENG', value: 'MATENG' },
  { name: 'specialities.HYDENG', value: 'HYDENG' },
  { name: 'specialities.ENVENG', value: 'ENVENG' },
  { name: 'specialities.MINENG', value: 'MINENG' },
  { name: 'specialities.NSEDU', value: 'NSEDU' },
  { name: 'specialities.HISTGEOEDU', value: 'HISTGEOEDU' },
  { name: 'specialities.PREPMATH', value: 'PREPMATH' },
  { name: 'specialities.PREPPHYS', value: 'PREPPHYS' },
  { name: 'specialities.PREPTECH', value: 'PREPTECH' },
  { name: 'control.other', value: 'other' }
];

const filterOptions = [
  { name: 'control.all', value: 'all' },
  { name: 'control.popular', value: 'popular' },
  { name: 'control.newest', value: 'newest' },
  { name: 'control.rate', value: 'rate' },
  { name: 'control.simple', value: 'simple' },
  { name: 'control.advanced', value: 'advanced' },
  
]

export default {
  univs,
  levels,
  specialities,
  filterOptions
}